### ISSUE TITLE
Jena vs. Blazegraph - Wikidata

### ISSUE THREAD

**Issue by r-clancy** [dstlry/dstlr#10]
Jena - https://jena.apache.org/documentation/tdb/commands.html#tdbloader2
Blazegraph - https://wiki.blazegraph.com/wiki/index.php/Bulk_Data_Load

Load in Wikidata (`/tuna1/scratch/dstlr/wikidata.nt`) and test point query + full-text search.

**Comment by r-clancy** [comment]
- Run on `tuna`
- Bump up Jena to `31G` heap
- Setup Blazegraph + full-text search (https://wiki.blazegraph.com/wiki/index.php/FullTextSearch)

**Comment by KaisongHuang** [comment]
Loading `wikidata.nt` into Blazegraph is stuck on this error. There must be some dirty statement in `wikidata.nt`.
```
ERROR: LexiconConfiguration.java:728: "0000-01-01T00:00:00Z" is not a valid representation of an XML Gregorian Calendar value.: value=0000-01-01T00:00:00Z
```

**Comment by r-clancy** [comment]
I'm creating a copy of the `wikidata.nt` file without those lines now... will message you when done.

**Comment by r-clancy** [comment]
I've removed the 15 lines causing issues, check out `/tuna1/scratch/dstlr/wikidata.blazegraph.nt`

**Comment by KaisongHuang** [comment]
> I've removed the 15 lines causing issues, check out `/tuna1/scratch/dstlr/wikidata.blazegraph.nt`

It worked.

**Comment by KaisongHuang** [comment]
Jena's loading and indexing are finished. 
Check the log here: `/tuna1/scratch/dstlr/dbs/jena/jena_load_wikidata.log`

**Comment by KaisongHuang** [comment]
# 1. Indexing
Total 1,237,309,635 triples.\
It took 8h for Jena to finish.\
It took 32h for Blazegraph to finish.

# 2. Point Query
|        | Jena | Blazegraph |
|-------:|----------:|-------:|
| "facebook” `Q355` |0.195s | 1.322s|
| "manhattan" `Q11299` |0.491s | 1.547s|
| "mona Lisa” `Q12418` |0.167s | 0.848s|
| "donald trump” `Q22686` | 0.743s| 3.429s|
| "tom and jerry” `Q131144` | 0.170s| 0.580s|
|"Barack Obama" `Q76`|1.386s |2.381s |

# 3. Full Text Search (limit = 20)
|        | Jena | Blazegraph |
|-------:|----------:|-------:|
| "facebook” `Q355` | 28.176s| 27.529s|
| "manhattan" `Q11299` | 2.104s| 3.305s|
| "mona Lisa” `Q12418` | 0.460s|0.843s |
| "donald trump” `Q22686` | 27.471s| 25.353s|
| "tom and jerry” `Q131144` |138.577s |218.680s |
|"Barack Obama" `Q76`|27.772s | 312.928s|
