### ISSUE TITLE
Missing documentation about ingesting data

### ISSUE THREAD

**Issue by lintool** [dstlry/dstlr#13]
Hi @r-clancy - one of the things currently missing in the documentation is how to start with a corpus and do the actual ingestion. I.e., I have Washington Post corpus. What do I do now?

**Comment by r-clancy** [comment]
Addressed in #14.

All of the docs need an updated, actually. When we setup stuff again on himrod after the upgrades I'll take a run through the docs again.

**Comment by lintool** [comment]
Okay, let's leave the issue open for now as a reminder.

**Comment by lintool** [comment]
Closing in favor of more complete articulation of issues in #20
