### ISSUE TITLE
Jena vs. Lucene - Freebase

### ISSUE THREAD

**Issue by r-clancy** [dstlry/dstlr#3]
Compare the ingest, point query, and BFS (2-hop) performance on Freebase.

- `anserini` freebase [docs](https://github.com/castorini/anserini/blob/master/docs/freebase.md)

**Comment by KaisongHuang** [comment]
# 1. Indexing Freebase
|         | All      |  English Only|
|:-------|:----------:|:-------------:|
| Jena    | 28:03 h  | N/A (Doesn't support language selection)|
| Lucene  | 05:17 h  | 04:53 h |

# 2. Searching Freebase
## 2.1. Point Query
|        | Jena (with Fuseki)      |  Lucene (with Anserini)|
|:-------|:----------:|:-------:|
| "facebook” `fb:m.0xb7xmh` | 0.138s| 0.44s|
| "manhattan" `fb:m.0lrcq_3` | 0.119s| 0.513s|
| "mona Lisa” `fb:m.0mypfcc` | 0.084s| 0.553s|
| "donald trump” `fb:m.0tntmck` | 0.389s| 0.354s|
| "tom and jerry” `fb:m.03s3k9` | 0.717s| 0.622s|

NOTE: All the queries are based on indexes with all the language literals.

## 2.2. Full Text Search
According to Apache Jena's [documentation](https://jena.apache.org/documentation/query/text-query.html), the full text engine can be either Apache Lucene hosted with Jena on a single machine, or Elasticsearch for a large scale enterprise search application where the full text engine is potentially distributed across separate machines. 

# 3. Conclusion
Therefore, we assume that Jena is a better choice than Lucene.

**Comment by KaisongHuang** [comment]
Considering there were large spark tasks running on tuna when I did the point query experiments above, I replicated the experiments again on a new Microsoft Azure VM which has 4 cores and 16GB RAM. It turned out that Jena and Lucene both got faster overall, but Jena still did better.

|    MID    | Jena (with Fuseki)      |  Lucene (with Anserini)|
|-------:|:----------:|:-------:|
| "facebook” `fb:m.0xb7xmh` | 0.047s| 0.192s|
| "manhattan" `fb:m.0lrcq_3` | 0.035s| 0.177s|
| "mona Lisa” `fb:m.0mypfcc` | 0.031s| 0.145s|
| "donald trump” `fb:m.0tntmck` | 0.037s| 0.167s|
| "tom and jerry” `fb:m.03s3k9` | 0.028s| 0.161s|

**Comment by r-clancy** [comment]
Nice - so it looks like Jena is up to 5x faster than Lucene.

Can we sanity check the Jena + Lucene vs. Lucene only full-text search on the literals? That is, install the Lucene plugin for Jena and run a similar experiment for doing a query with a search term.

**Comment by KaisongHuang** [comment]
Here, we are comparing __*Jena + Lucene*__ and __*Lucene*__ using the same terms mentioned above with __no hits limit__.

|    Term    | Jena + Lucene (with Fuseki) | Jena + Lucene (with Fuseki) 2nd time |  Lucene (with Anserini) |
|-------:|----------:|-------:|---:|
| "facebook” | 35.110s| 9.105s| >300s|
| "manhattan"| 142.347s| 28.702s| >300s|
| "mona lisa”| 195.061s| 21.186s| >300s|
| "donald trump” | 245.464s| 58.273s| >300s|
| "tom and jerry” | 266.904s| 41.221s| >300s|

NOTE: I searched the same terms for another round and restarted the fuseki server before I executed each query (not sure if it cleared cache). Besides, I commented `System.out.println()` in `io.anserini.kg.LookupFreebaseNodes` to eliminate output time.

Set __hits = 20__.

|    Term    | Jena + Lucene (with Fuseki)|  Lucene (with Anserini) |
|-------:|----------:|-------:|
| "facebook” | 0.383s| 4.674s|
| "manhattan"| 0.422s| 4.841s|
| "mona lisa”| 0.501s| 4.459s|
| "donald trump” | 0.515s| 3.294s|
| "tom and jerry” | 0.719s| 2.651s|
